num_workers: 2
batch_size: 16
cuda: 1
weight_name: "latest"
enable_cudnn: True

checkpoint_dir: "/dpb"
model_name: PointGroup-PAPER_latest
enable_dropout: False

output_path: "/dpb/forward_scripts/output"
input_path: "/dpb/forward_scripts/input"

data:
  fold: 0

# Dataset specific
defaults:
  - dataset: ""
    optional: True
