num_workers: 2
batch_size: 16
cuda: 0
weight_name: "miou" # Used during resume, select with model to load from [miou, macc, acc..., latest]
enable_cudnn: True
checkpoint_dir: "/home/lena.nahrwold/master-thesis/ForAINet/ForAINet/PointCloudSegmentation/forward_scripts/output/2025-09-03/13-12-00" # "{your_path}/outputs/2020-01-28/11-04-13" for example
model_name: TOTO
enable_dropout: False
output_path: "/home/lena.nahrwold/master-thesis/ForAINet/ForAINet/PointCloudSegmentation/forward_scripts/output" # Where the output goes
input_path: "/home/lena.nahrwold/master-thesis/ForAINet/ForAINet/PointCloudSegmentation/forward_scripts/input" # Folder where to find the data

# Dataset specific
defaults:
    - dataset: ""
      optional: True