num_workers: 2
batch_size: 16
cuda: 1
weight_name: "latest"
enable_cudnn: True

checkpoint_dir: "/dpb/models"
model_name: PointGroup-PAPER_latest
enable_dropout: False

input_path: "/dpb/data"
output_path: "/dpb/output"

data:
  task: custom
  dataroot: "/dpb/data"
  class: ufg_inference.PLYInferenceDataset
  fold: []
  num_classes: 5

# Dataset specific
defaults:
  - dataset: "ufg_inference"
    optional: True
